### ISSUE TITLE
Document difference between serde_tuple and serde_tuple_macros

### ISSUE THREAD

**Issue by nyurik** [kardeiz/serde_tuple#10]
crates.io has two crates with identical documentation - [serde_tuple](https://crates.io/crates/serde_tuple) and  [serde_tuple_macros](https://crates.io/crates/serde_tuple_macros). Please add some documentation which of the crates should be used in which case, or if they are identical - obsolete one to reduce the confusion. Thanks!

**Comment by nyurik** [comment]
@kardeiz I'm a bit confused - you still have identical description strings for both crates, even after bumping it to v1

**Comment by kardeiz** [comment]
Sorry, I meant to add a note that `serde_tuple_macros` was for internal use only. Having the two crates was necessary for libraries that have both proc-macro and standard code at the time. Not sure if this is still the case.

**Comment by nyurik** [comment]
@kardeiz thx for quick reply.  I meant that these two lines are identical, and cause confusion:
* https://github.com/kardeiz/serde_tuple/blob/2af6ceaafa0bf4e327469d165b4dcf98a82df838/Cargo.toml#L6
* https://github.com/kardeiz/serde_tuple/blob/2af6ceaafa0bf4e327469d165b4dcf98a82df838/serde_tuple_macros/Cargo.toml#L6

If you modify the second one to indicate that its an internal macro crate, it might help. Thx!
