### ISSUE TITLE
Add LICENSE file and distribute it in the crates

### ISSUE THREAD

**Issue by nullr0ute** [kardeiz/serde_tuple#11]
There should be a MIT LICENSE file in the repo and also included in the crate manifest.

**Comment by kardeiz** [comment]
@nullr0ute I added a LICENSE file as requested, though I am not sure what you mean by "included in the crate manifest"?

**Comment by decathorpe** [comment]
Speaking as another Fedora Linux package maintainer, I'm not sure either - but it would be great if you could publish a new version of the crate that includes the license file.

**Comment by decathorpe** [comment]
Can confirm that v1.0.0 crates (both serde_tuple and serde_tuple_macros) now contain the license text 🥳  feel free to close this ticket.
