### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by theduke** [kardeiz/serde_tuple#4]
Hey, thanks for implementing this.

A comment for a potential 0.2: the naming of the derives is a bit weird.

Why not `SerializeTuple` / `DeserializeTuple`?

**Comment by dtolnay** [comment]
The naming convention is meant to indicate that this derive macro is deriving the `Serialize` trait, but it is the `tuple` version of that derive logic. I find `SerializeTuple` misleading because there is no such trait as `SerializeTuple`.

**Comment by theduke** [comment]
That's an interesting and valid point.

It is somewhat misleading. I personally would not have associated the underscore separator with this distinction though. 

It's an interesting problem in terms of API design.

Maybe another way to draw a distinction would be to provide attribute macros instead of derives.
