### ISSUE TITLE
Parsing array with 1 field is not possible

### ISSUE THREAD

**Issue by benoist** [kardeiz/serde_tuple#9]
Hi,

I'm trying to parse an array of arguments and convert it to a struct. It works great for when the struct contains more than 1 field, but when it's 1 field, it doesn't work as I would have expected.

```rust
#[derive(Deserialize_tuple)]
struct DoubleParam {
  id : u64,
  my_arg : String
}

#[derive(Deserialize_tuple)]
struct SingleParam {
  id: u64
}

// works
serde_json::from_str::<DoubleParam>(r#"[1, "my arg"]"#)
// fails with invalid type: sequence, expected a u64
serde_json::from_str::<SingleParam>(r#"[2]"#)
```

**Comment by benoist** [comment]
If I expand the macro it appears that the sequence visitor is added, however it also adds the visit_newtype_struct and uses 

```rust
_serde::Deserializer::deserialize_newtype_struct(
    __deserializer,
    "SingleParam",
    __Visitor {
        marker: _serde::__private::PhantomData::<Inner>,
        lifetime: _serde::__private::PhantomData,
    },
)
  ```
  
The Double param macro expansion generates 
  
  ```rust
  _serde::Deserializer::deserialize_tuple_struct(
    __deserializer,
    "DoubleParam",
    2usize,
    __Visitor {
        marker: _serde::__private::PhantomData::<Inner>,
        lifetime: _serde::__private::PhantomData,
    },
)
```

**Comment by benoist** [comment]
It look like the default Deserialize for a tuple struct with 1 element uses the newtype struct.
As Deserialize_tuple adds the #[derive(Deserialize)] on the Inner tuple struct, it doesn't use the sequence but it uses the newtype_struct

**Comment by benoist** [comment]
As a possible solution could be to change the Inner struct to a ```[<Type>; 1]``` slice if it only contains 1 argument

So the macro would expand to

```rust
#[derive(Deserialize_tuple)]
struct SingleParam {
  id: u64
}

// Macro expansion
impl<'de> serde::Deserialize<'de> for SingleParam {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let [id] : [u64;1] = serde::Deserialize::deserialize(deserializer)?;
        Ok(SingleParam { id })
    }
}
```

**Comment by kardeiz** [comment]
Hi @benoist , can you confirm you are on version `0.5.0` (released 2020-03-20) of this crate? I believe this is more or less the same issue as https://github.com/kardeiz/serde_tuple/issues/6, which was fixed in that version.

I just tried it out and your example code runs fine on 0.5.0.

**Comment by benoist** [comment]
Oh dear, I apologise. I should have checked the versions better.
Thanks for the reply.
